/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * FmrHonorarios.java
 *
 * Created on 18/02/2014, 09:14:43
 */
package Formularios;
//import Honorarios_Custas.BuscasCustas_200;

import Honorarios_Custas.BuscasHonorarios;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;//import java.util.Random;
//import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author f7057419
 */
public class FmrHonorarios extends javax.swing.JFrame {

    /**
     * Creates new form fmrHonorariosCustas
     */
    public FmrHonorarios() {
        initComponents();

        txtChave.setText(System.getProperty("user.name").toUpperCase());
        txtSenha.requestFocus();
        //Altera a cor do formulário
        //Color corDoformulario = new Color(0,56,168);//Azul do banco
        //Random gerador = new Random(); 
        //int R = gerador.nextInt(256);
        //int G = gerador.nextInt(256);
        //int B = gerador.nextInt(256);          
        //Color corDoformulario = new Color(R,G,B);
        Color corDoformulario = new Color(145, 170, 252);
        getContentPane().setBackground(corDoformulario); //Aqui o método chave
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //Altera o tamanho do form
        // setBounds(300, 200, 400, 300);
        setBounds(600, 400, 605, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdHonorarios = new javax.swing.JToggleButton();
        txtChave = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtProgresso = new javax.swing.JTextField();
        txtMsgFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HONORÁRIOS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(145, 170, 252));
        setResizable(false);
        getContentPane().setLayout(null);

        cmdHonorarios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cmdHonorarios.setForeground(new java.awt.Color(0, 0, 204));
        cmdHonorarios.setText("Honorários");
        cmdHonorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHonorariosActionPerformed(evt);
            }
        });
        getContentPane().add(cmdHonorarios);
        cmdHonorarios.setBounds(10, 200, 320, 120);

        txtChave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChave.setText("F");
        txtChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChaveKeyReleased(evt);
            }
        });
        getContentPane().add(txtChave);
        txtChave.setBounds(130, 130, 107, 30);

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(360, 130, 128, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Chave:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 82, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 130, 82, 29);

        jPanel1.setBackground(new java.awt.Color(124, 147, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 580, 90);

        jLabel4.setBackground(new java.awt.Color(145, 170, 252));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Honorarios_Custas/img/bb_logo.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 420, 60, 61);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Honorarios_Custas/img/hand_3_2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(435, 240, 150, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Honorarios_Custas/img/TEXTO.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 580, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Honorarios_Custas/img/nome.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 480, 280, 20);

        jButton1.setBackground(new java.awt.Color(145, 170, 252));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Honorarios_Custas/img/SAIRM.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 420, 60, 60);

        txtProgresso.setBackground(new java.awt.Color(145, 170, 252));
        txtProgresso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtProgresso.setForeground(new java.awt.Color(51, 0, 204));
        txtProgresso.setBorder(null);
        getContentPane().add(txtProgresso);
        txtProgresso.setBounds(10, 330, 320, 20);

        txtMsgFinal.setBackground(new java.awt.Color(145, 170, 252));
        txtMsgFinal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMsgFinal.setForeground(new java.awt.Color(0, 102, 51));
        txtMsgFinal.setBorder(null);
        txtMsgFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgFinalActionPerformed(evt);
            }
        });
        getContentPane().add(txtMsgFinal);
        txtMsgFinal.setBounds(10, 350, 320, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdHonorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHonorariosActionPerformed
    //TODO add your handling code here:
    BuscasHonorarios BH = new BuscasHonorarios(txtChave.getText(), txtSenha.getText());
    try {
        BH.capturaInfos(this);
    } catch (IOException | InterruptedException | ParseException | SQLException ex) {
        Logger.getLogger(FmrHonorarios.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_cmdHonorariosActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jButton1ActionPerformed

    private void txtChaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChaveKeyReleased
        // TODO add your handling code here:
        int size = txtChave.getText().length();
        if (size == 8) {
            txtSenha.requestFocus();
        }
        if (size > 8) {
            txtChave.setText(txtChave.getText().substring(0, 8));
        }
    }//GEN-LAST:event_txtChaveKeyReleased

    private void txtMsgFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgFinalActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrHonorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FmrHonorarios().setVisible(true);
            }
        });
    }

    public void mudaTextoTeste(String texto) {//Exibe texto no formulário de progresso das linhas tratadas             
        txtProgresso.setText(texto);
        txtProgresso.paintAll(txtProgresso.getGraphics());//Atualiza a tela      
    }

    public void mudaTextoTeste1(String texto) { //Exibe texto no formulário de quantas linhas foram inseridas no banco            
        txtMsgFinal.setText(texto);
        txtMsgFinal.paintAll(txtMsgFinal.getGraphics());//Atualiza a tela       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cmdHonorarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtMsgFinal;
    private javax.swing.JTextField txtProgresso;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
