/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teste.java
 *
 * Created on 10/03/2014, 12:31:08
 */
package Formularios;

import DAO.Conexao;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 *
 * @author f7057419
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
      
  // Optional, if not specified, WebDriver will search your path for chromedriver.
  System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");

  WebDriver driver = new ChromeDriver();
  driver.get("http://www.google.com/xhtml");
        try {
            Thread.sleep(5000);  // Let the user actually see something!
        } catch (InterruptedException ex) {
            Logger.getLogger(teste.class.getName()).log(Level.SEVERE, null, ex);
        }
  WebElement searchBox = driver.findElement(By.name("q"));
  searchBox.sendKeys("ChromeDriver");
  searchBox.submit();
        try {
            Thread.sleep(5000);  // Let the user actually see something!
        } catch (InterruptedException ex) {
            Logger.getLogger(teste.class.getName()).log(Level.SEVERE, null, ex);
        }
  driver.quit();

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        String texto1 = " 'EVENTssssO' ";
        String texto2 = "20/02/2014";

        String dia = texto2.substring(0, 2);
        System.out.println(dia);
        String mes = texto2.substring(3, 5);
        System.out.println(mes);
        String ano = texto2.substring(6, 10);
        System.out.println(ano);
        String dataHonorariosBd = "'" + ano + "-" + mes + "-" + dia + "'";
        System.out.println(dataHonorariosBd);

        Connection cn = (Connection) new Conexao().conectar();
             //  String sqlGrava = "INSERT INTO hc_honor VALUES (null,'2001-01-01','2013/0209395-000','EVENTO','CONTRATADO','300.00','MODO REMUNERAÇAO','SITUACAO','F1234567','D','2002-02-02','11','2003-03-03','F1234567');";
        // String sqlGrava = "INSERT INTO hc_honor VALUES (null,'2001-01-01','2013/0209395-000', "+ texto1 +" ,'CONTRATADO','300.00','MODO REMUNERAÇAO','SITUACAO','F1234567','D','2002-02-02','11','2003-03-03','F1234567');";
        //  String sqlGrava = "INSERT INTO hc_honor VALUES (null," + texto2 + ",'2013/0209395-000', " + texto1 + " ,'CONTRATADO','300.00','MODO REMUNERAÇAO','SITUACAO','F1234567','d','2002-02-02','11','2003-03-03','F1234567');";

        String sqlGrava = "INSERT INTO hc_honor_antiga VALUES (null," + texto2 + ",'2013/0209395-000', " + texto1 + " ,'CONTRATADO_teste','300.00','MODO REMUNERAÇAO','SITUACAO','F1234567'," + "''" + ",'0000-00-00','11',now(),'F1234567');";

        //
        Statement stm = null;
        try {
            stm = (Statement) cn.createStatement();
        } catch (SQLException ex) {
        }

        int rs = 0;
        try {
            rs = stm.executeUpdate(sqlGrava);
        } catch (SQLException ex) {
        }

        if (rs != 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Dados gravados com sucesso!",
                    "Arrecadação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Falha",
                    "Arrecadação",
                    JOptionPane.INFORMATION_MESSAGE);

        }
        try {
            cn.close();//Fechar a conexão
            //--Fim da gravação no banco
        } catch (SQLException ex) {
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new teste().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
